# Generated by Django 5.0.7 on 2024-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pnr", "0002_station_notification_parcel_message_traveldetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="destination",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="origin",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
